name = "PLEnuM-registry"
uuid = "7197df97-4db2-493e-ad31-852b32964bfb"
repo = "git@github.com:PLEnuM-group/julia-registry.git"
description = "PLEnUM local registry for Julia packages"

[packages]
aacfb283-0df6-49c4-85a4-270b72c3b0a9 = { name = "PhysicsTools", path = "P/PhysicsTools" }
